language: go
sudo: required

go:
  - "1.12"
  - "1.13"
  - master

script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
  - env GO111MODULE=on make lint && make test && make bench
